"""maybe

Revision ID: 34826422c778
Revises: 33e0c8f35d02
Create Date: 2023-06-07 13:40:28.678954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34826422c778'
down_revision = '33e0c8f35d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
