"""Add user_data column to session_log table

Revision ID: c4393ed50b7d
Revises: 4b663a20d6d0
Create Date: 2023-06-12 12:32:45.509428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4393ed50b7d'
down_revision = '4b663a20d6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_logs')
    with op.batch_alter_table('session_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_log', schema=None) as batch_op:
        batch_op.drop_column('user_data')

    op.create_table('session_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_start', sa.DATETIME(), nullable=False),
    sa.Column('session_end', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_session_logs_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
